feat(dashboard): add links for panel
apache/devlake pull request #6755
Opened 2024-01-05 10:03 UTC by d4x1

### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [x] I have added relevant tests.
- [x] I have added relevant documentation.
- [x] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
What does this PR do?
Add links for every panel.

### Does this close any open issues?
Close #6722

### Screenshots
Include any relevant screenshots here.
![image](https://github.com/apache/incubator-devlake/assets/5844806/adc0eadb-182c-4fb0-8ee0-8397ce60a170)

### Other Information
Any other information that is important to this PR.

2024-01-05 11:23 UTC, d4x1 commented
These links are generated by https://github.com/merico-dev/devlake-tester/blob/main/dashboard/main.py .

2024-01-10 08:13 UTC, Startrekzky requested changes

2024-01-10 08:13 UTC, Startrekzky commented on grafana/dashboards/DORA.json
> +          "url": "https://devlake.apache.org/docs/Plugins/DORA"
The link is wrong. For DORA, it's https://devlake.apache.org/docs/DORA . However, you can get this whole thing removed, because it's already added.
![image](https://github.com/apache/incubator-devlake/assets/14050754/66b184e2-8e79-4925-a0b3-d239ebff1ccf)

2024-01-10 08:13 UTC, Startrekzky commented on grafana/dashboards/DORAByTeam.json
> +          "url": "https://devlake.apache.org/docs/Plugins/DORAByTeam"
Please delete this whole block too, because there's no doc for this.

2024-01-10 08:13 UTC, Startrekzky commented on grafana/dashboards/DORADebug.json
> +          "url": "https://devlake.apache.org/docs/Plugins/DORADebug"
Same as above.

2024-01-10 08:13 UTC, Startrekzky commented on grafana/dashboards/EngineeringOverview.json
> +          "url": "https://devlake.apache.org/docs/Plugins/EngineeringOverview"
There's no plugin doc for Engineering Overview.

2024-01-10 08:13 UTC, Startrekzky commented on grafana/dashboards/EngineeringOverview.json
> +          "url": "https://devlake.apache.org/docs/Metrics/LeadTimeForChanges"
This should be https://devlake.apache.org/docs/Metrics/PRTimeToMerge

2024-01-10 08:13 UTC, Startrekzky commented on grafana/dashboards/EngineeringOverview.json
> +          "url": "https://devlake.apache.org/docs/Metrics/LeadTimeForChanges"
This should be https://devlake.apache.org/docs/Metrics/PRTimeToMerge

2024-01-10 08:13 UTC, Startrekzky commented on grafana/dashboards/EngineeringOverview.json
> +          "url": "https://devlake.apache.org/docs/Metrics/CQIssueCount"
It's better to use 'Requirement Count' instead of 'CQ issue count'. https://devlake.apache.org/docs/Metrics/RequirementCount

Another solution is to add a metrics page called 'Issue Count' and link it to the panel.

2024-01-10 08:13 UTC, Startrekzky commented on grafana/dashboards/EngineeringThroughputAndCycleTime.json
> +          "url": "https://devlake.apache.org/docs/Plugins/EngineeringThroughputAndCycleTime"
No such plugin doc.

2024-01-10 08:13 UTC, Startrekzky commented on grafana/dashboards/EngineeringThroughputAndCycleTimeTeamView.json
> +          "url": "https://devlake.apache.org/docs/Plugins/EngineeringThroughputAndCycleTimeTeamView"
No such plugin doc.

2024-01-10 08:13 UTC, Startrekzky commented on grafana/dashboards/GithubReleaseQualityAndContributionAnalysis.json
> +          "url": "https://devlake.apache.org/docs/Plugins/GithubReleaseQualityAndContributionAnalysis"
No such plugin doc.

2024-01-10 08:13 UTC, Startrekzky commented on grafana/dashboards/WeeklyBugRetro.json
> +          "url": "https://devlake.apache.org/docs/Plugins/WeeklyBugRetro"
No such plugin doc.

2024-01-10 08:13 UTC, Startrekzky commented on grafana/dashboards/WeeklyCommunityRetro.json
> +          "url": "https://devlake.apache.org/docs/Plugins/WeeklyCommunityRetro"
No such plugin doc.

2024-01-11 11:51 UTC, d4x1 commented on grafana/dashboards/WeeklyCommunityRetro.json
> +          "url": "https://devlake.apache.org/docs/Plugins/WeeklyCommunityRetro"
Got it, it is generated by a script, there seems to be a bug, and I have fixed it.

2024-01-11 11:52 UTC, d4x1 commented on grafana/dashboards/WeeklyBugRetro.json
> +          "url": "https://devlake.apache.org/docs/Plugins/WeeklyBugRetro"
Got it, it is generated by a script, there seems to be a bug, and I have fixed it.

2024-01-11 11:52 UTC, d4x1 commented on grafana/dashboards/GithubReleaseQualityAndContributionAnalysis.json
> +          "url": "https://devlake.apache.org/docs/Plugins/GithubReleaseQualityAndContributionAnalysis"
Got it, it is generated by a script, there seems to be a bug, and I have fixed it.

2024-01-11 11:52 UTC, d4x1 commented on grafana/dashboards/EngineeringThroughputAndCycleTimeTeamView.json
> +          "url": "https://devlake.apache.org/docs/Plugins/EngineeringThroughputAndCycleTimeTeamView"
Got it, it is generated by a script, there seems to be a bug, and I have fixed it.

2024-01-11 11:52 UTC, d4x1 commented on grafana/dashboards/EngineeringThroughputAndCycleTime.json
> +          "url": "https://devlake.apache.org/docs/Plugins/EngineeringThroughputAndCycleTime"
Got it, it is generated by a script, there seems to be a bug, and I have fixed it.

2024-01-11 11:59 UTC, d4x1 commented on grafana/dashboards/EngineeringOverview.json
> +          "url": "https://devlake.apache.org/docs/Metrics/CQIssueCount"
Got it.

2024-01-11 12:02 UTC, d4x1 commented on grafana/dashboards/EngineeringOverview.json
> +          "url": "https://devlake.apache.org/docs/Metrics/LeadTimeForChanges"
Got it.

2024-01-11 12:02 UTC, d4x1 commented on grafana/dashboards/EngineeringOverview.json
> +          "url": "https://devlake.apache.org/docs/Metrics/LeadTimeForChanges"
Got it.

2024-01-11 12:02 UTC, d4x1 commented on grafana/dashboards/EngineeringOverview.json
> +          "url": "https://devlake.apache.org/docs/Plugins/EngineeringOverview"
Got it.

2024-01-11 12:02 UTC, d4x1 commented on grafana/dashboards/DORADebug.json
> +          "url": "https://devlake.apache.org/docs/Plugins/DORADebug"
Got it.

2024-01-11 12:03 UTC, d4x1 commented on grafana/dashboards/DORAByTeam.json
> +          "url": "https://devlake.apache.org/docs/Plugins/DORAByTeam"
Got it

2024-01-13 07:43 UTC, Startrekzky commented on grafana/dashboards/EngineeringThroughputAndCycleTime.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
We have another choice in terms of the URL: https://devlake.apache.org/docs/Metrics/RequirementGranularity

However, the RequirementCount is fine for me.

2024-01-13 08:52 UTC, Startrekzky requested changes

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Jira.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
It should be https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate.

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Jira.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
It should be https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Jira.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
It should be https://devlake.apache.org/docs/Metrics/RequirementLeadTime

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Jira.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
It should be https://devlake.apache.org/docs/Metrics/RequirementLeadTime

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Jira.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
It should be https://devlake.apache.org/docs/Metrics/RequirementLeadTime

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/TAPD.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/TAPD.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/TAPD.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/TAPD.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/TAPD.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Teambition.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Teambition.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Teambition.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Teambition.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Teambition.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Teambition.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementLeadTime"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Zentao.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Zentao.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Zentao.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Zentao.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Zentao.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/Zentao.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementLeadTime"
This is more like https://devlake.apache.org/docs/Metrics/RequirementDeliveryRate

2024-01-13 08:52 UTC, Startrekzky commented on grafana/dashboards/WeeklyBugRetro.json
> +          "url": "https://devlake.apache.org/docs/Metrics/BugCountPer1kLinesOfCode"
I'm OK with it now, but I think it can be improved later by adding a new metric doc and linking to it.

2024-01-16 06:58 UTC, d4x1 commented on grafana/dashboards/Zentao.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementLeadTime"
Fixed.

2024-01-16 06:58 UTC, d4x1 commented on grafana/dashboards/WeeklyBugRetro.json
> +          "url": "https://devlake.apache.org/docs/Metrics/BugCountPer1kLinesOfCode"
ok

2024-01-16 06:58 UTC, d4x1 commented on grafana/dashboards/Zentao.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed

2024-01-16 06:59 UTC, d4x1 commented on grafana/dashboards/Zentao.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 07:00 UTC, d4x1 commented on grafana/dashboards/Zentao.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 07:00 UTC, d4x1 commented on grafana/dashboards/Zentao.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 07:01 UTC, d4x1 commented on grafana/dashboards/Zentao.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed

2024-01-16 07:02 UTC, d4x1 commented on grafana/dashboards/Teambition.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementLeadTime"
fixed.

2024-01-16 07:03 UTC, d4x1 commented on grafana/dashboards/Teambition.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 07:03 UTC, d4x1 commented on grafana/dashboards/Teambition.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 07:06 UTC, d4x1 commented on grafana/dashboards/Teambition.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 07:07 UTC, d4x1 commented on grafana/dashboards/Teambition.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed

2024-01-16 07:07 UTC, d4x1 commented on grafana/dashboards/TAPD.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 07:07 UTC, d4x1 commented on grafana/dashboards/TAPD.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 07:08 UTC, d4x1 commented on grafana/dashboards/TAPD.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed

2024-01-16 07:08 UTC, d4x1 commented on grafana/dashboards/TAPD.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 07:08 UTC, d4x1 commented on grafana/dashboards/TAPD.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 07:09 UTC, d4x1 commented on grafana/dashboards/Jira.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 07:09 UTC, d4x1 commented on grafana/dashboards/Jira.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 07:14 UTC, d4x1 commented on grafana/dashboards/Jira.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 07:14 UTC, d4x1 commented on grafana/dashboards/Jira.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed

2024-01-16 07:15 UTC, d4x1 commented on grafana/dashboards/GithubReleaseQualityAndContributionAnalysis.json
> +          "url": "https://devlake.apache.org/docs/Metrics/BugCountPer1kLinesOfCode"
fixed.

2024-01-16 07:15 UTC, d4x1 commented on grafana/dashboards/GitHub.json
> +          "url": "https://devlake.apache.org/docs/Metrics/PRMergeRate"
fixed

2024-01-16 07:16 UTC, d4x1 commented on grafana/dashboards/GitHub.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 07:16 UTC, d4x1 commented on grafana/dashboards/GitHub.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 07:17 UTC, d4x1 commented on grafana/dashboards/GitHub.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 07:17 UTC, d4x1 commented on grafana/dashboards/EngineeringThroughputAndCycleTime.json
> +          "url": "https://devlake.apache.org/docs/Metrics/RequirementCount"
fixed.

2024-01-16 13:26 UTC, Startrekzky approved these changes
LGTM

2024-01-16 13:27 UTC, merged