feat(azuredevops): implement work items as issues
apache/devlake pull request #7809
Opened 2024-08-01 02:19 UTC by slaterx

### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [ ] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [ ] I have added relevant tests.
- [ ] I have added relevant documentation.
- [ ] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
This PR adds support for Azure DevOps work items as issues. The main thing to consider is that in Azure DevOps, work items are connected to projects and orgs, not repositories. Furthermore, current API definitions in Azure DevOps have a few limitations on retrieving work items data. Finally, work item queries are heavy and consume a lot of TSTUs, meaning that a simple query can impact overall organization usage of Azure DevOps and block access to services.

Thus, the decision was to:

- Break down the retrieval into two API calls, one to obtain the work item ids (using the WQL API) and another one to obtain the actual work items in small chunks (using the work item batch API), avoiding throttling issues.
- Use custom code instead of default converter code to store data in issues table.
- Add issue UI components to azure devops page scope configuration.
- Add issue dashboard panels to Azure DevOps grafana page, but remove repository reference from queries.

### Does this close any open issues?
Closes #5996

### Screenshots
![image](https://github.com/user-attachments/assets/e35e6c33-ef12-4643-a490-a170f2360f98)

### Other Information
With all work items collected, and their boards stored as component, having incidents mapped is as easy as querying work items with `type = bug`.

2024-08-05 19:15 UTC, mr-ks requested changes
Could you please check the GitHub Actions workflow? Some of the checks are failing e.g the [golangci-lint check](https://github.com/apache/incubator-devlake/actions/runs/10190826555)

2024-08-05 19:15 UTC, mr-ks commented on backend/plugins/azuredevops_go/tasks/workitem_collector.go
> +		if len(currentWorkItems) == 9 || key.Int() == int64(len(rawWorkItems.Array())-1) {
Can you please explain how you came up with this condition? Is this a restriction of the `/workitemsbatch` API?

2024-12-11 00:24 UTC, closed without merging

2026-06-16 05:17 UTC, magiskboy commented
have any progess in this pr?

2026-06-16 14:08 UTC, klesh commented
> have any progess in this pr?

It was closed in 2024.