fix: updating bitbucket server reference URLs to the working url
apache/devlake pull request #7921
Opened 2024-08-19 13:27 UTC by jmherbst

### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [x] I have added relevant tests.
- [x] I have added relevant documentation.
- [x] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
Updates a broken link.
"Check out this doc" link for Bitbucket Server "Manage Connections" page takes you to a `404` `https://devlake.apache.org/docs/Configuration/BitBucket-Server`
It looks like the correct link is `https://devlake.apache.org/docs/Configuration/BitBucketServer/`

### Does this close any open issues?
Closes xx

2024-08-20 02:34 UTC, klesh requested changes

2024-08-20 02:34 UTC, klesh commented on config-ui/src/release/v0.21.ts
> +        'https://devlake.apache.org/docs/v0.21/Configuration/BitBucketServer#step-3---adding-transformation-rules-optional',
The URLs should be https://devlake.apache.org/docs/v0.21/Configuration/BitBucket/ in v0.21

2024-08-20 14:58 UTC, jmherbst commented on config-ui/src/release/v0.21.ts
> +        'https://devlake.apache.org/docs/v0.21/Configuration/BitBucketServer#step-3---adding-transformation-rules-optional',
Thanks @klesh - I just pushed 00fb1d0 to correct this.

Now the `BITBUCKET` block matches the `BITBUCKET_SERVER` block in v0.21. Is that correct?

2024-08-21 03:00 UTC, klesh approved these changes
LGTM, Thanks for your contribution.

2024-08-21 03:00 UTC, merged